apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yourapp
  template:
    metadata:
      labels:
        app: yourapp
    spec:
      containers:
      - name: yourapp
        image: intel/intel-optimized-clickhouse
        ports:
        - containerPort: 3000
