apiVersion: v1
kind: Service
metadata:
  name: yourapp-service
spec:
  selector:
    app: yourapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
Resources:
  Deployment:
    Type: AWS::ApiGateway::Deployment